#!/bin/bash

type -P uglifyjs  &>/dev/null || { echo "Install UglifyJS (https://github.com/mishoo/UglifyJS) in order to minify JS"; exit 1; }

if [ `uname` == 'Darwin' ]
then
	chrome="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
elif [[ `which google-chrome` ]]
then
	chrome=`which google-chrome`
elif [ -z $YOUTUBE_TAMER_CHROME ]
then
	chrome=$YOUTUBE_TAMER_CHROME
else
	echo "Export Chrome's executable binary as YOUTUBE_TAMER_CHROME and run again!"
	exit 1
fi

chromeArgs="--pack-extension=/tmp/svs-tamer"

if [ -e './svs-tamer.pem' ]
then
	chromeArgs="$chromeArgs --pack-extension-key=./svs-tamer.pem"
fi

# Clean our tmp directory out
rm -r /tmp/svs-tamer 2>/dev/null
rm /tmp/svs-tamer.* 2>/dev/null
rm svs-tamer.zip svs-tamer.crx 2>/dev/null

mkdir /tmp/svs-tamer
cp manifest.json /tmp/svs-tamer/manifest.json
uglifyjs -nc svs-tamer.js > /tmp/svs-tamer/svs-tamer.js

current=`pwd`
"$chrome" $chromeArgs
mv /tmp/svs-tamer.crx $current
cd /tmp
zip -r "$current/svs-tamer.zip" svs-tamer
